const DEFAULT_CONFIG = {
  name:'RanzRyuu', tagline:'Menulis cerita, membangun bot, dan menciptakan dunia digital dengan energi kitsune.',
  bio:'RanzRyuu adalah identitas digital untuk berkarya, berbagi, dan membangun koneksi. Dari desain anime sampai automation bot, semuanya dibuat dengan sentuhan merah, putih, hitam, dan sedikit kegilaan kitsune.',
  botName:'RimuruMD', botDescription:'Bot pintar untuk menemani aktivitas digitalmu.', botWhatsapp:'60xxxxxx', wallpaper:'', platforms:[]
};
let config = {...DEFAULT_CONFIG};
const ADMIN_PATH = '/ranzryuuxxnx/adminih';
const SUPABASE_URL = 'https://zeiqupzxpgvuecmoiofb.supabase.co';
const SUPABASE_KEY = 'sb_publishable_UD9fW5dF8pRkZ9KMa6GUsA_UfROxXvV';
const SUPABASE_HEADERS = { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json' };
const $ = (selector, root=document) => root.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function bindData(){ document.querySelectorAll('[data-bind]').forEach(el=>{ const key=el.dataset.bind; if(config[key] !== undefined) el.textContent=config[key]; }); }
function normalizeWa(number){ return String(number || '').replace(/[^\d]/g,'') || '60xxxxxx'; }
function renderPlatforms(){ const grid=$('#platform-grid'); if(!grid) return; grid.innerHTML=(config.platforms || []).map((p,i)=>`<a class="platform-card" href="${esc(p.url || '#')}" target="_blank" rel="noopener"><span class="platform-number">0${i+1}</span><h3>${esc(p.name)}</h3><p>${esc(p.handle)}</p></a>`).join(''); }
function renderSite(){ bindData(); renderPlatforms(); document.body.style.setProperty('--wallpaper', config.wallpaper ? `url(\"${config.wallpaper}\")` : 'none'); const wa=normalizeWa(config.botWhatsapp); const bot=$('#bot-link'); if(bot) bot.href=`https://wa.me/${wa}`; const year=$('#year'); if(year) year.textContent=new Date().getFullYear(); }
function getStored(){ try{return JSON.parse(localStorage.getItem('ranzryuuConfig') || 'null')}catch{return null} }
async function loadConfig(){ try{ const remote=await fetch(`${SUPABASE_URL}/rest/v1/site_config?id=eq.main&select=config&limit=1&t=${Date.now()}`,{headers:SUPABASE_HEADERS,cache:'no-store'}); const rows=await remote.json(); if(remote.ok && rows[0]?.config && Object.keys(rows[0].config).length){ config={...DEFAULT_CONFIG,...rows[0].config}; localStorage.setItem('ranzryuuConfig',JSON.stringify(config)); renderSite(); return; } }catch(e){ console.warn('Supabase belum tersedia, memakai fallback.'); } const stored=getStored(); if(stored){ config={...DEFAULT_CONFIG,...stored}; renderSite(); return; } try{ const configUrl=location.hostname.endsWith('github.io') ? '/ranzryuu-portfolio/config.json' : '/config.json'; const res=await fetch(configUrl); if(res.ok) config={...DEFAULT_CONFIG,...await res.json()}; }catch(e){ console.warn('config.json tidak ditemukan, memakai default.'); } renderSite(); }
async function saveRemoteConfig(){ const response=await fetch(`${SUPABASE_URL}/rest/v1/site_config?id=eq.main`,{method:'PATCH',headers:{...SUPABASE_HEADERS,Prefer:'return=minimal'},body:JSON.stringify({config,updated_at:new Date().toISOString()})}); if(!response.ok) throw new Error('Supabase save failed'); }
function showToast(message){ const toast=$('#toast'); if(!toast)return; toast.textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2400); }
function setupMenu(){ const button=$('.menu-toggle'), nav=$('.nav-links'); button?.addEventListener('click',()=>nav.classList.toggle('open')); nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open'))); }
const ADMIN_USER = 'Ranz';
const ADMIN_PASS_HASH = '8b6297567c8a54194fb6cf48df9d34a2f26d017422a2c8b291b05197af880942';
async function sha256(value){ const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
function showAdminLogin(){ document.body.innerHTML=`<div class="admin-page"><header class="site-header"><a class="brand" href="/"><span class="brand-mark">狐</span><span>RanzRyuu Admin</span></a><a class="admin-back" href="/">← Kembali ke portfolio</a></header><main class="login-shell"><div class="login-card"><p class="eyebrow"><span></span> Restricted area</p><h1>ADMIN<span>.</span></h1><p class="login-subtitle">Masuk untuk mengatur profile, bot, dan platform.</p><form id="login-form"><label>Username<input name="username" autocomplete="username" required /></label><label>Password<input name="password" type="password" autocomplete="current-password" required /></label><p id="login-error" class="login-error" aria-live="polite"></p><button class="button button-red" type="submit">Masuk ke Settings ↗</button></form></div></main></div>`; $('#login-form').onsubmit=async e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(e.currentTarget)); const valid=data.username===ADMIN_USER && await sha256(data.password)===ADMIN_PASS_HASH; if(!valid){$('#login-error').textContent='Username atau password salah.'; return;} sessionStorage.setItem('ranzryuuAdmin','authenticated'); adminView();}; }
function adminView(){ document.body.innerHTML=`<div class="admin-page"><header class="site-header"><a class="brand" href="/"><span class="brand-mark">狐</span><span>RanzRyuu Admin</span></a><div class="admin-header-actions"><button class="admin-logout" id="logout">Logout</button><a class="admin-back" href="/">← Portfolio</a></div></header><main class="admin-shell"><div class="admin-intro"><p class="eyebrow"><span></span> Private control room</p><h1>SETTINGS<span>.</span></h1><p>Perubahan tersimpan di browser ini melalui localStorage. Untuk produksi multi-device, hubungkan form ini ke database/backend.</p></div><form id="settings-form"><section class="admin-card"><h2>Profile</h2><div class="form-grid"><label>Nama<input name="name" required /></label><label>Tagline<input name="tagline" /></label><label class="full">Bio<textarea name="bio" rows="4"></textarea></label><label class="full">Wallpaper URL<input name="wallpaper" placeholder="https://.../wallpaper.jpg" /></label></div></section><section class="admin-card"><h2>Bot</h2><div class="form-grid"><label>Nama Bot<input name="botName" /></label><label>Nomor WhatsApp<input name="botWhatsapp" placeholder="60123456789" /></label><label class="full">Deskripsi Bot<input name="botDescription" /></label></div></section><section class="admin-card"><div class="card-title-row"><h2>Platform</h2><button type="button" class="mini-button" id="add-platform">+ Tambah</button></div><div id="admin-platforms"></div></section><div class="admin-actions"><button class="button button-red" type="submit">Simpan Settings ↗</button><button class="button button-outline" type="button" id="reset-settings">Reset Default</button><button class="button button-outline" type="button" id="export-settings">Export JSON</button></div></form><p class="admin-note">Tip: edit <code>config.json</code> untuk nilai awal sebelum deployment. Link Admin: <code>/ranzryuuxxnx/adminih</code></p></main></div>`; $('#logout').onclick=()=>{sessionStorage.removeItem('ranzryuuAdmin'); showAdminLogin();}; populateAdmin(); }
function populateAdmin(){ const form=$('#settings-form'); ['name','tagline','bio','wallpaper','botName','botWhatsapp','botDescription'].forEach(k=>form.elements[k].value=config[k] || ''); renderAdminPlatforms(); $('#add-platform').onclick=()=>{config.platforms.push({name:'Platform Baru',handle:'Deskripsi singkat',url:'https://'}); renderAdminPlatforms()}; form.onsubmit=e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(form).entries()); config={...config,...data,platforms:readAdminPlatforms()}; localStorage.setItem('ranzryuuConfig',JSON.stringify(config)); saveRemoteConfig().then(()=>showToast('Settings tersimpan dan tersinkron ke semua device.')).catch(()=>showToast('Tersimpan lokal, tetapi sinkronisasi Supabase gagal.'));}; $('#reset-settings').onclick=()=>{localStorage.removeItem('ranzryuuConfig'); config={...DEFAULT_CONFIG}; populateAdmin(); showToast('Settings di-reset.');}; $('#export-settings').onclick=()=>{const blob=new Blob([JSON.stringify(config,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='ranzryuu-config.json'; a.click(); URL.revokeObjectURL(a.href);}; }
function renderAdminPlatforms(){ const wrap=$('#admin-platforms'); wrap.innerHTML=(config.platforms||[]).map((p,i)=>`<div class="platform-row" data-index="${i}"><input data-key="name" value="${esc(p.name)}" aria-label="Nama platform" /><input data-key="handle" value="${esc(p.handle)}" aria-label="Handle platform" /><input data-key="url" value="${esc(p.url)}" aria-label="URL platform" /><button type="button" class="remove-platform" aria-label="Hapus">×</button></div>`).join(''); wrap.querySelectorAll('.remove-platform').forEach(btn=>btn.onclick=()=>{btn.closest('.platform-row').remove()}); }
function readAdminPlatforms(){ return [...document.querySelectorAll('.platform-row')].map(row=>{const values=[...row.querySelectorAll('input')]; return Object.fromEntries(values.map(input=>[input.dataset.key,input.value]))}); }
function lightProtection(){ document.addEventListener('contextmenu',e=>e.preventDefault()); document.addEventListener('keydown',e=>{ if((e.ctrlKey||e.metaKey)&&['u','s'].includes(e.key.toLowerCase())) e.preventDefault(); }); }
async function init(){ lightProtection(); if(location.pathname.replace(/\/$/,'')===ADMIN_PATH){ await loadConfig(); sessionStorage.getItem('ranzryuuAdmin')==='authenticated' ? adminView() : showAdminLogin(); return; } await loadConfig(); setupMenu(); }
init();
